/*
 * Copyright 2021-2023 MONAI Consortium
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;
using Newtonsoft.Json;

namespace Monai.Deploy.Messaging.Events
{
    public class ExportRequestEvent : EventBase
    {
        /// <summary>
        /// Gets or sets the workflow instance ID generated by the Workflow Manager.
        /// </summary>
        [JsonProperty(PropertyName = "workflow_instance_id")]
        [JsonPropertyName("workflow_instance_id")]
        [Required]
        public string WorkflowInstanceId { get; set; } = default!;

        /// <summary>
        /// Gets or sets the export task ID generated by the Workflow Manager.
        /// </summary>
        [JsonProperty(PropertyName = "export_task_id")]
        [JsonPropertyName("export_task_id")]
        [Required]
        public string ExportTaskId { get; set; } = default!;

        /// <summary>
        /// Gets or sets a list of files to be exported.
        /// </summary>
        [JsonProperty(PropertyName = "files")]
        [JsonPropertyName("files")]
        [Required, MinLength(1)]
        public IEnumerable<string> Files { get; set; } = default!;

        /// <summary>
        /// Gets or sets the export target.
        /// For DIMSE, the named DICOM destination.
        /// For ACR, the Transaction ID in the original inference request.
        /// </summary>
        [JsonProperty(PropertyName = "destinations")]
        [JsonPropertyName("destinations")]
        [Required]
        public string[] Destinations { get; set; } = default!;

        /// <summary>
        /// Gets or set the correlation ID.
        /// For DIMSE, the correlation ID is the UUID associated with the first DICOM association received.
        /// For ACR, use the Transaction ID in the original request.
        /// </summary>
        [JsonProperty(PropertyName = "correlation_id")]
        [JsonPropertyName("correlation_id")]
        [Required]
        public string CorrelationId { get; set; } = default!;

        /// <summary>
        /// Gets or sets the delivery tag or acknowledge token for the task.
        /// </summary>
        [JsonProperty(PropertyName = "delivery_tag")]
        [JsonPropertyName("delivery_tag")]
        public string DeliveryTag { get; set; } = default!;

        /// <summary>
        /// Gets or sets the message ID set by the message broker.
        /// </summary>
        [JsonProperty(PropertyName = "message_id")]
        [JsonPropertyName("message_id")]
        public string MessageId { get; set; } = default!;

        /// <summary>
        /// Gets or sets error messages related to this export task.
        /// </summary>
        [JsonProperty(PropertyName = "error_messages")]
        [JsonPropertyName("error_messages")]
        public List<string> ErrorMessages { get; private set; }

        [JsonProperty(PropertyName = "file_id")]
        [JsonPropertyName("file_id")]
        public string? PayloadId { get; set; }

        /// <summary>
        /// A list of data output plug-in type names to be executed by the export services.
        /// Each string must be a fully-qualified type name.
        /// E.g. <code>MyCompnay.MyProject.MyNamepsace.MyPlugin, MyCompnay.MyProject.MyNamepsace</code> where
        /// <code>MyCompnay.MyProject.MyNamepsace</code> is the name of the assembly (DLL).
        /// </summary>
        [JsonProperty(PropertyName = "plug_in_assemblies")]
        [JsonPropertyName("plug_in_assemblies")]
        public List<string> PluginAssemblies { get; private set; }

        /// <summary>
        /// the target to export too
        /// </summary>
        public DataOrigin? Target { get; set; }

        public ExportRequestEvent()
        {
            ErrorMessages = new List<string>();
            PluginAssemblies = new List<string>();
        }

        public void AddErrorMessages(IList<string> errorMessages)
        {
            ErrorMessages.AddRange(errorMessages);
        }
    }
}
