// SPDX-FileCopyrightText: © 2021-2022 MONAI Consortium
// SPDX-License-Identifier: Apache License 2.0

using System.ComponentModel.DataAnnotations;
using Ardalis.GuardClauses;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Monai.Deploy.Messaging.Events
{
    public class ExportCompleteEvent : EventBase
    {
        /// <summary>
        /// Gets or sets the workflow ID generated by the Workflow Manager.
        /// </summary>
        [JsonProperty(PropertyName = "workflow_id")]
        [Required]
        public string WorkflowId { get; set; } = default!;

        /// <summary>
        /// Gets or sets the export task ID generated by the Workflow Manager.
        /// </summary>
        [JsonProperty(PropertyName = "export_task_id")]
        [Required]
        public string ExportTaskId { get; set; } = default!;

        /// <summary>
        /// Gets or sets the state of the export task.
        /// </summary>
        [JsonProperty(PropertyName = "status")]
        [JsonConverter(typeof(StringEnumConverter))]
        [Required]
        public ExportStatus Status { get; set; }

        /// <summary>
        /// Gets or sets error messages, if any, when exporting.
        /// </summary>
        [JsonProperty(PropertyName = "message")]
        public string Message { get; set; } = default!;

        [JsonConstructor]
        public ExportCompleteEvent()
        {
            Status = ExportStatus.Unknown;
        }

        public ExportCompleteEvent(ExportRequestEvent exportRequest)
        {
            Guard.Against.Null(exportRequest, nameof(exportRequest));

            WorkflowId = exportRequest.WorkflowId;
            ExportTaskId = exportRequest.ExportTaskId;
            Message = string.Join(System.Environment.NewLine, exportRequest.ErrorMessages);

            if (exportRequest.FailedFiles == 0)
            {
                Status = ExportStatus.Success;
            }
            else if (exportRequest.FailedFiles == exportRequest.Files.Count())
            {
                Status = ExportStatus.Failure;
            }
            else
            {
                Status = ExportStatus.PartialFailure;
            }
        }
    }
}
